#import "/i18n-scope.typ": *
#let live-item-data = (
  "lorem": (
    8,
    [
      #babel(
        en: [
          Creates blind text.

          This function yields a Latin-like _Lorem Ipsum_ blind text with the given
          number of words. The sequence of words generated by the function is always
          the same but randomly chosen. As usual for blind texts, it does not make any
          sense. Use it as a placeholder to try layouts.
        ],
      )

      = #babel(en: [Example]) <example>
      ```example
      = Blind Text
      #lorem(30)

      = More Blind Text
      #lorem(15)
      ```
    ],
  ),
  "lorem::words": (
    25,
    babel(
      en: [
        The length of the blind text in words.
      ],
    ),
  ),
)
