name: Build
on:
  push:
    branches:
      - base
      - locale
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:
  docit:
    uses: ./.github/workflows/cache-docit.yml

  build:
    runs-on: ubuntu-latest
    needs: docit
    steps:
      - uses: actions/checkout@v7
      - uses: taiki-e/install-action@v2
        with:
          tool: just
      - run: just setup

      - name: Setup docit
        uses: actions/cache/restore@v6
        with:
          key: ${{ needs.docit.outputs.key }}
          path: target/typst-docs
          fail-on-cache-miss: true
      - name: Prepare to upload
        run: |
          cd target/
          tar cJf docit.tar.xz typst-docs
      - name: Upload docit for human contributors
        uses: actions/upload-artifact@v7
        with:
          name: docit.tar.xz
          path: target/docit.tar.xz
          archive: false

      - run: just build
      - uses: actions/upload-artifact@v7
        with:
          name: docs-website
          path: target/dist/site
      - uses: actions/upload-artifact@v7
        with:
          name: docs-pdf
          path: target/dist/docs.pdf

  check:
    runs-on: ubuntu-latest
    needs: docit
    steps:
      - uses: actions/checkout@v7
      - uses: taiki-e/install-action@v2
        with:
          tool: just, sd, fd-find, typstyle
      - run: just setup
      - name: Setup docit
        uses: actions/cache/restore@v6
        with:
          key: ${{ needs.docit.outputs.key }}
          path: target/typst-docs
          fail-on-cache-miss: true

      - name: Run just fmt
        run: |
          just fmt
          git add --all
          git diff --exit-code --staged
      - name: Run just save-patches
        run: |
          just save-patches
          git add --all
          git diff --exit-code --staged

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: scripts/babelize/
      - run: rustup target add wasm32-unknown-unknown
      - run: cargo test
        working-directory: scripts/babelize/
      - run: cargo check --all-targets
        working-directory: scripts/babelize/
      - run: cargo clippy --all-targets
        working-directory: scripts/babelize/
      - run: just setup-babelize
      - uses: actions/upload-artifact@v7
        with:
          name: babelize-wasm
          path: scripts/babelize/target/wasm32-unknown-unknown/release/babelize.wasm

      - name: Make sure `just export-i18n` does not depend on locale/
        run: rm -r locale/
      - run: just export-i18n
      - name: Make sure locale/ is up to date
        if: ${{ github.base_ref == 'base' || github.ref_name == 'base' }}
        run: |
          mv target/i18n-export/ locale/
          git add --all
          git diff --exit-code --staged
